### ISSUE TITLE
Passwords are generated differently after the Chrome extension was updated

### ISSUE THREAD

**Issue by thaiphv** [lesspass/lesspass#148]
After the Chrome extension was updated, I'm no longer able to generate the passwords that I used to use to login in my sites. They all complained that my passwords were incorrect.

**Comment by guillaumevincent** [comment]
@thaiphv can you check if site is the same?
With version 2 by default autofill site change. Site like `www.example.org` become `example.org`.
And `sudomain.example.org` become `example.org`

**Comment by guillaumevincent** [comment]
Sorry, I think that when version 2 was active, auto fill use the new rules: 
`www.example.org` become `example.org` and `sudomain.example.org` become `example.org`

And it's not
I will fix this breaking change right now!
Sorry about that

**Comment by guillaumevincent** [comment]
@thaiphv can you confirm the new version is ok?

**Comment by thaiphv** [comment]
Thanks for your swift action. Do I need to update the Chrome extension in order to verify it?

**Comment by guillaumevincent** [comment]
@thaiphv you will be able to see the version 2.3.2 soon.
I have already published the corrected version. I'm waiting for Chrome to release the version everywhere.
The web extension will be updated automatically.

**Comment by guillaumevincent** [comment]
@thaiphv thanks to you for warning me

**Comment by thaiphv** [comment]
@guillaumevincent I'm still unable to obtain my passwords after upgrading the Chrome extension to 2.3.2. I don't know if any of the default advanced options have been changed after the upgrades but none of my saved profiles worked.

**Comment by guillaumevincent** [comment]
@thaiphv Harmony use LessPass version 2 for default options:
See https://github.com/lesspass/lesspass/releases/tag/harmony

So default options loaded now are:
```
{
    lowercase: true,
    uppercase: true,
    numbers: true,
    symbols: true,
    length: 16,
    counter: 1,
    version: 2,
};
```

**Comment by edouard-lopez** [comment]
@thaiphv I couldn't replicate either. 

* [ ] is the site correct (with/without subdomain)?
* [ ] did your visual checksum changed?
* [ ] did you verify your options (version, charsets, etc.)?

Let us know if it's ok for you.

**Comment by thaiphv** [comment]
Found the issue. I also installed the extension for Firefox and I was able to regenerate my passwords on it. I loaded a saved password profile, then hit on the settings icon, after that switching between V1 and V2. On the Firefox extension, the V1 password length is 12 and the V2 one is 16. I had started using V2 passwords for a few weeks already so I think all of my passwords' length is 16. However, the Chrome extension preset both V1 and V2 password length to 12.

**Comment by edouard-lopez** [comment]
@guillaumevincent switching between v1 and v2 doesn't change the `length` config. I'm always having a length of `16` character that might be the cause of the problem for @thaiphv.

**Comment by guillaumevincent** [comment]
you're right!
thanks @edouard-lopez and @thaiphv 

I'm going to push the fix

**Comment by guillaumevincent** [comment]
fix in web extension version 2.3.4

**Comment by thaiphv** [comment]
@guillaumevincent, thanks. It's fixed now.
