### ISSUE TITLE
Firefox extension hides on master password field focus

### ISSUE THREAD

**Issue by Yajo** [lesspass/lesspass#170]
Title says it all...

**Comment by guillaumevincent** [comment]
@Yajo when you focus master password field, Firefox popup closes?

**Comment by edouard-lopez** [comment]
@Yajo I can't reproduce on Firefox `52.0b9 (64-bit)` with LessPass `2.3.4`.

Could you provide the following:
1. steps to reproduce ;
1. Firefox version ;
1. LessPass version.

**Comment by Yajo** [comment]
> when you focus master password field, Firefox popup closes?

Yes, exactly. 

1.    steps to reproduce: See [screencast.zip](https://github.com/lesspass/lesspass/files/820474/screencast.zip).
2.    Firefox version: 51.0.1 (64-bit)
3.    LessPass version. 2.3.4

**Comment by edouard-lopez** [comment]
@Yajo I installed the same Firefox and LessPass version but still can't reproduce.

![lesspass- 170](https://cloud.githubusercontent.com/assets/1212392/23604696/0c2d2af2-025a-11e7-9358-5d5412eb1321.gif)

Can you try on a new Firefox profile, so we rule out side effect from other add-ons:

    firefox --no-remote --ProfileManager  # create a new profile to test

In the meantime you can use the website [lesspass.com](http://lesspass.com/), it uses the same code than the add-on.

**Comment by guillaumevincent** [comment]
@Yajo can you try with the new Firefox 52? thank you

**Comment by Yajo** [comment]
Yikes, empty profile and FF 52, and still the same bug. Is there any debug info I can provide?

**Comment by guillaumevincent** [comment]
fuck :(
I suppose that already reinstalled LessPass extension.

you can debug the web extension and see if an error is printed:

 * open new tab and go to `about:debugging#addons`
 * check `Enable add-on debugging`
 * click on `DEBUG` button for LessPass
 * accept incoming connection and open console tab
 * keep debug window open, and play with LessPass

**Comment by edouard-lopez** [comment]
@Yajo did you solve your problem?

**Comment by guillaumevincent** [comment]
There is a new version of LessPass  Firefox extension.
I close this one, feel free to tell us in this issue if you still have the problem

**Comment by Yajo** [comment]
Sorry, LessPass 2.3.5 and still happens. I tried to debug, but nothing in the logs seems relevant:

```
Evento de teclado no disponible en algunas configuraciones de teclado: key=“r” modifiers=“accel,alt” id=“toggleReaderMode”  browser.xul
Evento de teclado no disponible en algunas configuraciones de teclado: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox”  browser.xul
Public-Key-Pins: el certificado usado por el sitio no fue emitido por un certificado en el almacén de certificados raíz por defecto. Para prevenir rupturas de confianza accidentales, se ha ignorado la cabecera especificada.[Saber más]  profile
Public-Key-Pins: el certificado usado por el sitio no fue emitido por un certificado en el almacén de certificados raíz por defecto. Para prevenir rupturas de confianza accidentales, se ha ignorado la cabecera especificada.[Saber más] repair
Content Security Policy: No se puede procesar la directiva desconocida 'worker-src'  (desconocido)
Content Security Policy: La directiva 'frame-src' está desaprobada. Use la directiva 'child-src' en su lugar.  (desconocido)
Public-Key-Pins: el certificado usado por el sitio no fue emitido por un certificado en el almacén de certificados raíz por defecto. Para prevenir rupturas de confianza accidentales, se ha ignorado la cabecera especificada.[Saber más]  recipe
Public-Key-Pins: el certificado usado por el sitio no fue emitido por un certificado en el almacén de certificados raíz por defecto. Para prevenir rupturas de confianza accidentales, se ha ignorado la cabecera especificada.[Saber más]  classify_client
Public-Key-Pins: el certificado usado por el sitio no fue emitido por un certificado en el almacén de certificados raíz por defecto. Para prevenir rupturas de confianza accidentales, se ha ignorado la cabecera especificada.[Saber más]  console-log
Public-Key-Pins: el certificado usado por el sitio no fue emitido por un certificado en el almacén de certificados raíz por defecto. Para prevenir rupturas de confianza accidentales, se ha ignorado la cabecera especificada.[Saber más]  stats
Public-Key-Pins: el certificado usado por el sitio no fue emitido por un certificado en el almacén de certificados raíz por defecto. Para prevenir rupturas de confianza accidentales, se ha ignorado la cabecera especificada.[Saber más]  211945831
POST 
http://ocsp.digicert.com/ [Contenido mixto]
[HTTP/1.1 200 OK 71ms]
POST 
http://ocsp.digicert.com/ [Contenido mixto]
[HTTP/1.1 200 OK 70ms]
GET 
XHR 
http://detectportal.firefox.com/success.txt [Contenido mixto]
[HTTP/1.1 200 OK 51ms]
```

I tried to debug and it seems it has something to do with an onclick event binded in the body I think, but code is minified so I cannot understand well (and code formatter does not work, gasp!)

**Comment by guillaumevincent** [comment]
@Yajo Do you want a zip extension with non minified version to debug?

**Comment by Yajo** [comment]
Yes, it could help.

**Comment by guillaumevincent** [comment]
Remove `.zip` extension:
[lesspass.firefox.xpi.zip](https://github.com/lesspass/lesspass/files/889379/lesspass.firefox.xpi.zip)

You can inspect the .xpi file (it's a zip)
`lesspass.min.js` in not minified in this one

**Comment by guillaumevincent** [comment]
@Yajo Do you have some time trying to debug the web extension?

**Comment by guillaumevincent** [comment]
I close this one @Yajo 
There are 600 users each day on Firefox and it seems that you are the only one to encounter this problem. Sorry, if we have more information to debug, I would be happy to try to solve the problem.

**Comment by Yajo** [comment]
I've been trying to debug the problem this morning, but no clue. The problem is the debugging tools themselves: I cannot set up a breakpoint without the extension closing, and if I disable the auto-closing of the popup, then of course the bug does not appear, since the bug is an undesired autoclose. Pressing F8 to pause JS until I click does not pause it, I have no idea on how to workaround the tools to debug them, but this really keeps on happening to me. Do you have an idea on that? 😕

**Comment by guillaumevincent** [comment]
No I don't 😕 

I don't understand why the extension doesn't work with `firefox --no-remote --ProfileManager`
With new profile, you should not get the error.

When I see your logs, there a lot of text. With no extension installed, you should not have those warning.

`Content Security Policy: La directiva 'frame-src' está desaprobada. Use la directiva 'child-src' en su lugar.  (desconocido)` another extension maybe raise this error.
And you have some error with certificates. 

Those errors are not related to LessPass, but these errors should not appear.
**Does the extension work with Chrome?**

**Comment by guillaumevincent** [comment]
@Yajo if you have node and git installed on your computer you can try the debug mode of the web extension directly:

    git clone https://github.com/lesspass/webextension
    npm install && npm run dev

**Comment by dajbelshaw** [comment]
@guillaumevincent I love LessPass, but for the last couple of months (can't pin it down to a particular release) I've only been able to use the Chrome extension. 
Here's what happens in Firefox (regular/Nightly, have tried new profile) on Ubuntu 18.04:

![Attempt to tab into master password box](https://user-images.githubusercontent.com/2429426/41477688-f7a19d0c-70bc-11e8-978a-4a8bb2c7a4ee.gif)
Attempt to tab into master password field

![Attempt to click on master password field](https://user-images.githubusercontent.com/2429426/41477723-1457cb4c-70bd-11e8-987f-a7ba09e0d4da.gif)
Attempt to click on master password field

I wonder if @Yajo is using Ubuntu 18.04 too?

**Comment by guillaumevincent** [comment]
@dajbelshaw it's probably related to https://github.com/lesspass/lesspass/issues/329

**Comment by Yajo** [comment]
That was my bug, yes, although I just checked today and it seems fixed in my current environment. I've been using the lesspass site since then.

I use Fedora BTW (version 28 since not much long ago).

**Comment by Yajo** [comment]
Lol, it started happening again...

**Comment by kemelzaidan** [comment]
I'm having the same issue and it very annoying! And it's certainly not fixed...

**Comment by guillaumevincent** [comment]
@kemelzaidan I close this one because it duplicates https://github.com/lesspass/lesspass/issues/329
Feel free to open another issue if it's not the same bug
