### ISSUE TITLE
[cli] Password prompt shows password on Windows

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#305]
Hello,
When using lesspass-cli 5.0.1 on Windows 7 with Bash, the password is displayed when typed:
![image](https://user-images.githubusercontent.com/840125/34045915-667877f6-e1ab-11e7-96f2-30ee781331a2.png)

The Bash I'm using is the one provided by [Git for Windows](http://gitforwindows.org/).
I can't however reproduce with Windows original command prompt.

At first I thought it was a limitation of the Mingw Bash but `read -s` works correctly.

**Comment by edouard-lopez** [comment]
I can't reproduce on Linux with bash `4.3.48`. @sctfic do you have this kind of issue?

Could you give more info about your software versions?

**Comment by Rudloff** [comment]
Here is more info about the versions I'm using:
* Bash 4.4.12
* Node 9.3.0
* mintty 2.8.1

I can't reproduce on Debian with 4.4.12 either, so I really think this is specific to Windows.

**Comment by Rudloff** [comment]
I just noticed something strange.

This reproduces the issue:
```bash
env node cli.js foo
```

This does not:
```bash
node cli.js foo
```

**Comment by guillaumevincent** [comment]
Probably related to https://github.com/npm/read/issues/34

**Comment by monolifed** [comment]
You can try https://github.com/monolifed/lesspassc
Downside is you have to build it yourself and commandline options are a little different.

**Comment by monolifed** [comment]
There is a similar issue that was fixed in mute-stream 0.0.6 which is used by read
https://github.com/npm/mute-stream/issues/3
But read uses `"mute-stream": "~0.0.4"` as dependency
Not sure if it is relevant

**Comment by Rudloff** [comment]
`~0.0.4` means that currently 0.0.7 is installed, so it does not seam to be the same issue.

**Comment by monolifed** [comment]
Yes, ~0.0.4 should allow 0.0.x but it looked similar to the issue posted by @guillaumevincent and 
Is the following one more relevant to your issue?
https://github.com/npm/read/issues/29

**Comment by Rudloff** [comment]
Yes, this seems to be the same issue.

**Comment by guillaumevincent** [comment]
Hello @Rudloff 
can you confirm the bug is still present with lesspass-cli version 5.0.2 ?
Thanks

**Comment by Rudloff** [comment]
Yes, I can still reproduce with 5.0.2.

**Comment by guillaumevincent** [comment]
@Rudloff I pushed new version of lesspass-cli@5.1.0 with another module for reading password.
Can you test it and close this issue @Rudloff?

Thanks

**Comment by Rudloff** [comment]
Unfortunately, I can still reproduce with 5.1.0 :disappointed:

**Comment by guillaumevincent** [comment]
LessPass cli move on pypi and this bug is fixed:

    npm -g uninstall lesspass-cli
    python3 -m pip install --user lesspass

:warning:  breaking changes:

 * -c is associated with --copy flag to copy the password
 * -C is associated with the counter (previously -c)
